<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventGathera.Application\EventGathera.Application.csproj" />
    <ProjectReference Include="..\EventGathera.Domain\EventGathera.Domain.csproj" />
  </ItemGroup>

</Project>
